#ifndef _VCONF_H_
#define _VCONF_H_

#include <include/generated/autoconf.h>

#define TWANVISOR_ON CONFIG_TWANVISOR_ON
#define TWANVISOR_VIPI_DRAIN_STRICT CONFIG_TWANVISOR_VIPI_DRAIN_STRICT

#if TWANVISOR_ON

#define TWANVISOR_PV_LOCKS CONFIG_TWANVISOR_PV_LOCKS

#else 

#define TWANVISOR_PV_LOCKS 0

#endif 

#endif