#ifndef _SCHED_CONF_H_
#define _SCHED_CONF_H_

#include <include/kernel/boot.h>
#include <include/types.h>
#include <stdint.h>

#define SCHED_TASK_STACK_SIZE 2048
#define SCHED_TIME_SLICE_MS CONFIG_KERNEL_SCHED_TIME_SLICE_MS
STATIC_ASSERT(SCHED_TIME_SLICE_MS < UINT32_MAX);

#if NUM_CPUS > 0

#define SCHED_GLOBAL_QUEUE CONFIG_KERNEL_SCHED_GLOBAL_QUEUE

#else 

#define SCHED_GLOBAL_QUEUE 1

#endif

#define SCHED_NUM_QUEUES (SCHED_GLOBAL_QUEUE ? 1 : NUM_CPUS) 
#define SCHED_AGING CONFIG_KERNEL_SCHED_AGING

#define SCHED_NUM_CRITICALITIES CONFIG_KERNEL_SCHED_NUM_CRITICALITIES
STATIC_ASSERT(SCHED_NUM_CRITICALITIES >= 1 && 
              SCHED_NUM_CRITICALITIES <= UINT8_MAX);

#define LOAD_BALANCING_OFF 0
#define LOAD_BALANCING_CONSERVATIVE 1
#define LOAD_BALANCING_AGGRESSIVE 2

#if !SCHED_GLOBAL_QUEUE

extern u8 sched_load_balancing_conf[NUM_CPUS];

#endif

#endif